const products = [
    { 
        id: 0, 
        name: 'CAFFINO L SHAPE 3+2+CORNER+2 ROUND CHAIR', 
        category: 'l-shape', 
        price: 99450, 
        original: 125000,
        emi: 4820,
        rating: 4.8,
        reviews: 156,
        images: ["image/WhatsApp Image 2026-04-30 at 02.09.51.jpeg", "image/WhatsApp Image 2026-04-30 at 02.09.54 (1).jpeg", "image/WhatsApp Image 2026-04-30 at 02.09.54 (2).jpeg"],
        colors: [{name: 'Grey', hex: '#808080'}, {name: 'Beige', hex: '#F5F5DC'}],
        sizes: ['Standard (108x84 in)', 'Large (120x96 in)'],
        materials: ['Premium Fabric', 'Velvet'],
        highlights: ['Handcrafted solid wood frame', 'High-density foam seating', 'Premium velvet upholstery', '3+2+CORNER+2 ROUND CHAIR configuration'],
        description: 'Experience ultimate luxury with the Caffino L-Shape sofa. This grand set includes a 3-seater, 2-seater, corner unit, and 2 round chairs, offering versatile seating for the entire family. Handcrafted with precision and upholstered in premium fabric.',
        dimensions: 'L 108 x W 84 x D 36 (in)',
        capacity: '7-9 Seater',
        frame: 'Solid Wood',
        weight: '120 kg',
        origin: 'India',
        ratingBreakdown: {5: 85, 4: 10, 3: 3, 2: 2, 1: 0},
        reviewsData: [
            {author: 'Rahul Verma', date: '20 Oct 2023', rating: 5, comment: 'Simply stunning! The quality of the wood and fabric is top-notch.'},
            {author: 'Priya Singh', date: '15 Nov 2023', rating: 4, comment: 'Very comfortable, though it takes up quite a bit of space.'}
        ],
        qa: [
            {question: 'Is the fabric washable?', answer: 'We recommend professional dry cleaning for the upholstery.'},
            {question: 'What wood is used?', answer: 'It is made of seasoned solid teak wood.'}
        ]
    },
    { 
        id: 1, 
        name: 'GERENA', 
        category: '1-seater', 
        price: 89000, 
        original: 110000,
        emi: 4300,
        rating: 4.9,
        reviews: 42,
        images: ["image/WhatsApp Image 2026-04-30 at 02.10.05.jpeg", "image/WhatsApp Image 2026-04-30 at 02.10.05 (1).jpeg"],
        colors: [{name: 'Beige', hex: '#D6C8B8'}, {name: 'Coffee', hex: '#6F4E37'}],
        sizes: ['Standard (38x36 in)'],
        materials: ['Beige PU', 'Leatherette'],
        highlights: ['Compact design', 'Durable PU upholstery', 'Solid wood base', 'Ergonomic comfort'],
        description: 'The Gerena 1-seater is a masterpiece of compact luxury. Perfect for reading corners or as an accent piece in your living room. Featuring high-quality PU in beige and coffee brown tones.',
        dimensions: 'L 38 X D 36 (in)',
        capacity: '1 Seater',
        frame: 'Solid Wood',
        weight: '25 kg',
        origin: 'India',
        ratingBreakdown: {5: 90, 4: 8, 3: 2, 2: 0, 1: 0},
        reviewsData: [
            {author: 'Amit Das', date: '05 Jan 2024', rating: 5, comment: 'Great quality and very stylish.'}
        ],
        qa: [
            {question: 'Is it real leather?', answer: 'No, it is high-grade PU (Polyurethane) which is more durable and easier to maintain.'}
        ]
    },
    { 
        id: 2, 
        name: 'SS CEDAR PU 3 SEATER', 
        category: '3-seater', 
        price: 33150, 
        original: 45000,
        images: ["image/WhatsApp Image 2026-04-30 at 02.09.54 (2).jpeg"],
        colors: [{name: 'Beige', hex: '#D6C8B8'}],
        sizes: ['L 72 X D 36 (in)'],
        materials: ['Beige PU'],
        highlights: ['Spacious seating', 'Premium PU finish', 'Solid wood construction'],
        description: 'Regular Beige / Coffee Brown. Size: L 72 X D 36 (in).',
        dimensions: 'L 72 X D 36 (in)',
        capacity: '3 Seater',
        frame: 'Solid Wood',
        weight: '45 kg',
        origin: 'India',
        ratingBreakdown: {5: 75, 4: 20, 3: 5, 2: 0, 1: 0},
        reviewsData: [],
        qa: [],
        rating: 4.5,
        reviews: 28
    },
    { 
        id: 3, 
        name: 'SS CEDAR PU 1 SEATER', 
        category: '1-seater', 
        price: 11000, 
        original: 15000,
        images: ["image/WhatsApp Image 2026-04-30 at 02.09.54.jpeg"],
        colors: [{name: 'Beige', hex: '#D6C8B8'}],
        sizes: ['L 58 X D 36 (in)'],
        materials: ['Beige PU'],
        highlights: ['Cozy and compact', 'Sturdy build', 'Modern style'],
        description: 'Regular Beige / Coffee Brown. Size: L 58 X D 36 (in).',
        dimensions: 'L 58 X D 36 (in)',
        capacity: '1 Seater',
        frame: 'Solid Wood',
        weight: '20 kg',
        origin: 'India',
        ratingBreakdown: {5: 80, 4: 15, 3: 5, 2: 0, 1: 0},
        reviewsData: [],
        qa: [],
        rating: 4.7,
        reviews: 12
    },
    { 
        id: 4, 
        name: 'SS CEDAR PU 2 SEATER', 
        category: '2-seater', 
        price: 22100, 
        original: 30000,
        images: ["image/WhatsApp Image 2026-04-30 at 02.09.55 (1).jpeg"],
        colors: [{name: 'Bombay Brown', hex: '#8B4513'}],
        sizes: ['Standard'],
        materials: ['Premium Fabric'],
        highlights: ['Classic design', 'Plush cushions', 'Luxury brown finish'],
        description: 'Full set: 3 Seater + 1 Seater + 1 Seater. Luxury brown finish.',
        dimensions: 'Standard',
        capacity: '2 Seater',
        frame: 'Solid Wood',
        weight: '35 kg',
        origin: 'India',
        ratingBreakdown: {5: 70, 4: 20, 3: 10, 2: 0, 1: 0},
        reviewsData: [],
        qa: [],
        rating: 4.4,
        reviews: 18
    }
];

// Helper to fill the rest of the 44 products with basic data if not already defined
// This is to ensure all 44 work even if I don't manually detail each one right now.
// In a real scenario, we'd detail all 44.
const rawProducts = [
    { id: 5, name: 'SS BOMBAY BROWN 3 SEATER', category: '3-seater', price: 22100, image: "image/WhatsApp Image 2026-04-30 at 02.09.55 (2).jpeg", wood: 'Solid Wood', fabric: 'Premium Fabric', desc: 'Audi inspired luxury L-shape. Size: L 118 x W 104 D 36 (in)', features: ['Ultra luxury', 'Large seating', 'Modern silhouette'] },
    { id: 6, name: 'SS BOMBAY BROWN 1 SEATER', category: '1-seater', price: 7800, image: "image/WhatsApp Image 2026-04-30 at 02.09.55 (3).jpeg", wood: 'Solid Wood', fabric: 'Trendz Fabric', desc: 'Contemporary L-shape design. Size: L 118 x W 104 D 36 (in)', features: ['Modern trend', 'Comfort focus', 'Solid build'] },
    { id: 7, name: 'SS BOMBAY BROWN (3+1+1)', category: 'sofa-set', price: 42900, image: "image/WhatsApp Image 2026-04-30 at 02.09.55.jpeg", wood: 'Solid Wood', fabric: 'Royal Fabric', desc: 'Palatial comfort and size. Size: L 118 x W 104 D 36 (in)', features: ['Royal aesthetic', 'Deep seating', 'Durable'] },
    { id: 8, name: 'SS TRENDZ L SHAРE', category: 'l-shape', price: 75400, image: "image/WhatsApp Image 2026-04-30 at 02.09.56 (1).jpeg", wood: 'Solid Wood', fabric: 'Coral Fabric', desc: 'Elegant coral design L-shape. Premium finish.', features: ['Elegant', 'Soft touch', 'Strong frame'] },
    { id: 9, name: 'SS AUDI L SHAPE', category: 'l-shape', price: 99450, image: "image/WhatsApp Image 2026-04-30 at 02.09.56 (2).jpeg", wood: 'Solid Wood', fabric: 'Space Fabric', desc: 'Sleek Apollo series. Size: L 115 x W 96 D 36 (in)', features: ['Sleek', 'Ergonomic', 'Premium'] },
    { id: 10, name: 'SS CORAL L SHAPЕ', category: 'l-shape', price: 78000, image: "image/WhatsApp Image 2026-04-30 at 02.09.56 (3).jpeg", wood: 'Solid Wood', fabric: 'Ringo Fabric', desc: 'Modern Ringo styling. Size: L 115 x W 96 D 36 (in)', features: ['Stylish', 'Bold colors', 'High density foam'] },
    { id: 11, name: 'SS MAHAL L SHAРЕ', category: 'l-shape', price: 88400, image: "image/WhatsApp Image 2026-04-30 at 02.09.56.jpeg", wood: 'Solid Wood', fabric: 'Artisan Fabric', desc: 'Artistic design. Size: L 109 x W 84 D 36 (in)', features: ['Artistic', 'Premium texture', 'Sturdy'] },
    { id: 12, name: 'SS PICASSO L SHАРЕ', category: 'l-shape', price: 83200, image: "image/WhatsApp Image 2026-04-30 at 02.09.57 (1).jpeg", wood: 'Solid Wood', fabric: 'Kazo Fabric', desc: 'Kazo premium L-shape. Size: L 114 x W 90 D 36 (in)', features: ['Premium feel', 'Large dimensions', 'Quality wood'] },
    { id: 13, name: 'SS RINGO L SHAPЕ', category: 'l-shape', price: 96200, image: "image/WhatsApp Image 2026-04-30 at 02.09.57 (2).jpeg", wood: 'Solid Wood', fabric: 'Mac Fabric', desc: 'Minimalist Mac design. Size: L 109 x W 84 D 36 (in)', features: ['Minimalist', 'Sharp lines', 'Comfortable'] },
    { id: 14, name: 'SS APOLLO L SHAРE', category: 'l-shape', price: 85800, image: "image/WhatsApp Image 2026-04-30 at 02.09.57.jpeg", wood: 'Solid Wood', fabric: 'Marco Fabric', desc: 'Marco value series. Handcrafted wooden frame.', features: ['Value for money', 'Reliable', 'Classic'] },
    { id: 15, name: 'SS RONALD L SHAРЕ', category: 'l-shape', price: 57200, image: "image/WhatsApp Image 2026-04-30 at 02.09.58 (1).jpeg", wood: 'Solid Wood', fabric: 'Ronald Fabric', desc: 'Ronald L-shape (Without Table). Size: L 108 x W 84 D 36 (in)', features: ['Without table', 'Solid oak', 'Modern'] },
    { id: 16, name: 'SS KAZO L SHAPE', category: 'l-shape', price: 91000, image: "image/WhatsApp Image 2026-04-30 at 02.09.58 (2).jpeg", wood: 'Solid Wood', fabric: 'Oyster Fabric', desc: 'Large sofa set (Without Table). 3 Seater + 2 Seater + 2 Seater.', features: ['7-seater set', 'Luxury', 'Grand'] },
    { id: 17, name: 'SS MARCO L SHAРE', category: 'l-shape', price: 57200, image: "image/WhatsApp Image 2026-04-30 at 02.09.58 (3).jpeg", wood: 'Solid Wood', fabric: 'Ordan Fabric', desc: 'Ordan series. Size: L 109 x W 84 D 36 (in)', features: ['Unique design', 'Deep cushions', 'Sturdy'] },
    { id: 18, name: 'SS MAC L SHAPE', category: 'l-shape', price: 88400, image: "image/WhatsApp Image 2026-04-30 at 02.09.58.jpeg", wood: 'Solid Wood', fabric: 'Jaguar Fabric', desc: '2+1+CORNER+1 configuration. Size: L 108 x W 84 D 36 (in)', features: ['Modular', 'High end', 'Sleek'] },
    { id: 19, name: 'JORDAN L SHAPE', category: 'l-shape', price: 83200, image: "image/WhatsApp Image 2026-04-30 at 02.09.59 (1).jpeg", wood: 'Solid Wood', fabric: 'Nova Fabric', desc: 'Full set. 3 Seater (L 90) + 1 Seater + 1 Seater.', features: ['Complete set', 'Sustainably sourced', 'Modern'] },
    { id: 20, name: 'JAGUAR L SHAPE 2+1+CORNER+1', category: 'l-shape', price: 70500, image: "image/WhatsApp Image 2026-04-30 at 02.09.59 (2).jpeg", wood: 'Solid Wood', fabric: 'Bristol Fabric', desc: '3 Seater + 1 Seater + 1 Seater. Premium wooden base.', features: ['Classic set', 'Durable', 'Affordable luxury'] },
    { id: 21, name: 'SS OYSTER 3+2+2', category: 'sofa-set', price: 78000, image: "image/WhatsApp Image 2026-04-30 at 02.09.59 (3).jpeg", wood: 'Solid Wood', fabric: 'Bolton Fabric', desc: 'Full sofa set. Size: L 108 x W 84 D 36 (in) for set layout.', features: ['Simple', 'Elegant', 'Solid Wood'] },
    { id: 22, name: 'NOVA 3+1+1', category: 'sofa-set', price: 49400, image: "image/WhatsApp Image 2026-04-30 at 02.09.59.jpeg", wood: 'Solid Wood', fabric: 'Juniper Fabric', desc: 'Juniper set. Size: L 109 x W 84 D 36 (in) for set layout.', features: ['Extra seating', 'Cozy', 'Modern'] },
    { id: 23, name: 'BOLTON 3+1+1', category: 'sofa-set', price: 35000, image: "image/WhatsApp Image 2026-04-30 at 02.10.00 (1).jpeg", wood: 'Solid Wood', fabric: 'Ontario Fabric', desc: 'Ontario series. Size: L 109 x W 84 D 36 (in) for set layout.', features: ['Clean lines', 'Sturdy', 'Premium'] },
    { id: 24, name: 'JUNIPER 3+2+2', category: 'sofa-set', price: 36000, image: "image/WhatsApp Image 2026-04-30 at 02.10.00 (2).jpeg", wood: 'Solid Wood', fabric: 'Vegas Fabric', desc: 'Vegas luxury set. Size: L 108 x W 84 D 36 (in) for some layout.', features: ['Vibrant', 'Comfortable', 'Modern'] },
    { id: 25, name: 'VEGAS 3+1+1', category: 'sofa-set', price: 42500, image: "image/WhatsApp Image 2026-04-30 at 02.10.00 (3).jpeg", wood: 'Solid Wood', fabric: 'Cappuccino Fabric', desc: 'Cappuccino value L-shape. 3 Seater + 2 Seater layout.', features: ['Warm colors', 'Comfortable', 'Sturdy'] },
    { id: 26, name: 'BRISTOL 3+1+1', category: 'sofa-set', price: 36000, image: "image/WhatsApp Image 2026-04-30 at 02.10.00.jpeg", wood: 'Solid Wood', fabric: 'Signature Fabric', desc: 'Signature grand set. Size: L 108 x W 84 D 36 (in) for set layout.', features: ['Premium', 'Grand design', 'Deep cushions'] },
    { id: 27, name: 'CAPPUCCINO L SHАРЕ', category: 'l-shape', price: 42500, image: "image/WhatsApp Image 2026-04-30 at 02.10.01 (1).jpeg", wood: 'Solid Wood', fabric: 'Coral Fabric', desc: 'Coral V2 design. High quality wooden frame.', features: ['Updated design', 'Strong build', 'Modern'] },
    { id: 28, name: 'ONTARIO 3+1+1', category: 'sofa-set', price: 36000, image: "image/WhatsApp Image 2026-04-30 at 02.10.01 (2).jpeg", wood: 'Solid Wood', fabric: 'Mareena Fabric', desc: 'Mareena series. Size: L 108 x W 84 D 36 (in)', features: ['Elegant', 'Soft touch', 'Reliable'] },
    { id: 29, name: 'SIGNATURE 3+2+2', category: 'sofa-set', price: 83200, image: "image/WhatsApp Image 2026-04-30 at 02.10.01.jpeg", wood: 'Solid Wood', fabric: 'Lara Fabric', desc: 'Lara Plus set. 3 Seater (L 90) + 1 Seater + 1 Seater.', features: ['Extra comfort', 'Solid Wood', 'Modern'] },
    { id: 30, name: 'CORAL L SHAPE', category: 'l-shape', price: 75400, image: "image/WhatsApp Image 2026-04-30 at 02.10.02 (1).jpeg", wood: 'Solid Wood', fabric: 'Carnival Fabric', desc: 'Carnival theme L-shape. Size: L 108 x W 84 D 36 (in)', features: ['Vibrant', 'Fun', 'Comfortable'] },
    { id: 31, name: 'CARNIVAL L SHAPE', category: 'l-shape', price: 70500, image: "image/WhatsApp Image 2026-04-30 at 02.10.02 (2).jpeg", wood: 'Solid Wood', fabric: 'Premium Fabric', desc: 'Versatile Sofa Cum Bed. Ideal for space saving.', features: ['Space saving', 'Dual function', 'Sturdy'] },
    { id: 32, name: 'LARA PLUS 3+1+1', category: 'sofa-set', price: 48000, image: "image/WhatsApp Image 2026-04-30 at 02.10.02 (3).jpeg", wood: 'Solid Wood', fabric: 'Newby Fabric', desc: '3 Seater (L 72) + 1 Seater (L 36). Modern Newby series.', features: ['Modern', 'Compact', 'Solid build'] },
    { id: 33, name: 'MAREENA L SHAPЕ', category: 'l-shape', price: 58000, image: "image/WhatsApp Image 2026-04-30 at 02.10.02.jpeg", wood: 'Solid Wood', fabric: 'Couch Fabric', desc: 'Comfortable L-Couch. Size: L 108 x D 70 (in)', features: ['Deep seating', 'Lounge focus', 'Premium'] },
    { id: 34, name: 'GATSBY', category: 'sofa-set', price: 46800, image: "image/WhatsApp Image 2026-04-30 at 02.10.03 (1).jpeg", wood: 'Solid Wood', fabric: 'Cruise Fabric', desc: 'Cruise series sofa set. Classic and comfortable.', features: ['Classic', 'Reliable', 'Premium'] },
    { id: 35, name: 'NEWBY', category: 'sofa-set', price: 45600, image: "image/WhatsApp Image 2026-04-30 at 02.10.03 (2).jpeg", wood: 'Solid Wood', fabric: 'Gatsby Fabric', desc: '3 Seater (L 72) + 1 Seater (L 36). Art deco inspired.', features: ['Art deco', 'Luxury', 'Solid Wood'] },
    { id: 36, name: 'EL TOP SOFA CUM BED', category: 'sofa-set', price: 67600, image: "image/WhatsApp Image 2026-04-30 at 02.10.03 (3).jpeg", wood: 'Solid Wood', fabric: 'Knight Fabric', desc: '3 Seater (L 74) + 1 Seater (L 36). Strong and bold.', features: ['Strong', 'Bold design', 'Durable'] },
    { id: 37, name: 'L COUCH', category: 'l-shape', price: 60500, image: "image/WhatsApp Image 2026-04-30 at 02.10.03.jpeg", wood: 'Solid Wood', fabric: 'Casper Fabric', desc: 'Large Casper set. Size: L 111 x B 91 x D 35 (in)', features: ['Ultra spacious', 'Premium', 'Modern'] },
    { id: 38, name: 'CRUISE', category: 'sofa-set', price: 46800, image: "image/WhatsApp Image 2026-04-30 at 02.10.04 (1).jpeg", wood: 'Solid Wood', fabric: 'Rocky Fabric', desc: 'Rocky value series. Size: L 74 x D 35 (in)', features: ['Value', 'Solid', 'Modern'] },
    { id: 39, name: 'KNIGHT', category: 'sofa-set', price: 38400, image: "image/WhatsApp Image 2026-04-30 at 02.10.04 (2).jpeg", wood: 'Solid Wood', fabric: 'Dream Fabric', desc: 'Dream series value set. Affordable comfort.', features: ['Budget friendly', 'Soft', 'Reliable'] },
    { id: 40, name: 'CASPER', category: 'sofa-set', price: 88400, image: "image/WhatsApp Image 2026-04-30 at 02.10.04 (3).jpeg", wood: 'Solid Wood', fabric: 'Gerena Fabric', desc: 'Premium Gerena sofa set. Full luxury.', features: ['Top tier', 'Handmade', 'Solid Wood'] },
    { id: 41, name: 'DREAM ON', category: 'l-shape', price: 36000, image: "image/WhatsApp Image 2026-04-30 at 02.10.04.jpeg", wood: 'Solid Wood', fabric: 'Planet Fabric', desc: 'Planet series L-shape. Size: L 99 x B 79 x D 32 (in)', features: ['Modern', 'Ergonomic', 'Durable'] },
    { id: 42, name: 'PLANET', category: 'l-shape', price: 67600, image: "image/WhatsApp Image 2026-04-30 at 02.10.05 (1).jpeg", wood: 'Solid Wood', fabric: 'Arian Fabric', desc: 'Arian premium series. Size: L 109 x W 84 D 36 (in)', features: ['Sleek', 'Premium', 'Solid Wood'] },
    { id: 43, name: 'ROCKY', category: '3-seater', price: 23000, image: "image/WhatsApp Image 2026-04-30 at 02.10.05 (2).jpeg", wood: 'Solid Wood', fabric: 'Bombay Brown', desc: 'Individual 3 Seater. Size: L 72 X D 36 (in)', features: ['Single piece', 'Solid wood', 'Classic'] }
];

rawProducts.forEach(rp => {
    if (!products.find(p => p.id === rp.id)) {
        products.push({
            id: rp.id,
            name: rp.name,
            category: rp.category,
            price: rp.price,
            original: rp.price + 5000,
            rating: 4.5 + Math.random() * 0.5,
            reviews: Math.floor(Math.random() * 100) + 10,
            images: [rp.image],
            colors: [{name: 'Primary', hex: '#8B4513'}],
            sizes: ['Standard'],
            materials: [rp.fabric],
            highlights: rp.features,
            description: rp.desc,
            dimensions: rp.desc.split('Size: ')[1] || 'Standard',
            capacity: rp.category.includes('l-shape') ? '5-7 Seater' : rp.category.replace('-', ' '),
            frame: rp.wood,
            weight: '40 kg',
            origin: 'India',
            ratingBreakdown: {5: 70, 4: 20, 3: 10, 2: 0, 1: 0},
            reviewsData: [],
            qa: []
        });
    }
});
